truncate table `Prints`;
truncate table `AdditionalData`;
truncate table `Sets`;
truncate table `Legalities`;
truncate table `RelatedCards`;
truncate table `ImportFiles`;
truncate table `Cards`;
truncate table `Prices`;
truncate table `Collection`;
truncate table `CardFaces`;
alter sequence`id_seq` restart 1;